#!/bin/bash

set -ex

#server_ip=$(echo "$SSH_CLIENT" | awk '{ print $1 }')

export PULSE_SERVER="localhost"

while [ "$#" -gt 0 ]; do
    case "$1" in
	--new)
	    socket=$(mktemp --tmpdir pafwd.XXXXXX)

	    module_base_name=tunnel

	    dbus-launch \
		--exit-with-session \
		pulseaudio -n --disable-shm --use-pid-file=no \
		--log-target=syslog \
		--exit-idle-time=-1 \
		--load "module-native-protocol-unix socket=$socket" \
		--load "module-always-sink" \
		--load "module-null-sink sink_name=TX sink_properties=device.description='TX' rate=48000" \
		--load "module-switch-on-connect" \
		-vv --daemonize=yes
#		--load "module-rescue-streams" \
#		--load "module-intended-roles" \
#		--load "module-suspend-on-idle" \
#		--load "module-switch-on-port-available" \

	    export PULSE_SERVER="unix:$socket"
	    function killpulse {
		pactl exit
	    }
	    trap killpulse EXIT
	    parent=$$
	    (trap killpulse HUP; while true; do sleep 3600; done) &
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    fwdport=$1
	    module_base_name=tcp_localhost_$fwdport
	    ;;
    esac
    shift
done
if [ -n "$fwdport" ]; then
    export PULSE_SINK=tunnel-sink.$module_base_name
    export PULSE_SOURCE=tunnel-source.$module_base_name
    python - <<EOF
from pulsectl import Pulse
with Pulse('start-eme') as pulse:
  pulse.module_load('module-tunnel-sink', 'server=tcp:localhost:$fwdport sink_name=$PULSE_SINK rate=48000')
  pulse.module_load('module-tunnel-source', 'server=tcp:localhost:$fwdport source_name=$PULSE_SOURCE rate=48000')
EOF
    echo "PulseAudio connected"
fi

if [ $# -eq 0 ]; then
    exec "$SHELL" -l
else
    exec "$@"
fi
